### ISSUE TITLE
list index out of range error

### ISSUE THREAD

**Issue by hans-permana** [DeDop/dedop-core#39] opened 2017-09-12 13:43 UTC
### Expected behavior

DeDop can process Amazon L1A file.

### Actual behavior

Observed a `list index out of range` error.

![image](https://user-images.githubusercontent.com/7643370/30328546-f70703a8-97cf-11e7-9578-b51a76764725.png)

In DeDop Shell, it looks like this.

```cmd
> dedop run -i "C:\Users\hans\.dedop\workspaces\aaa\inputs\CS_LTA__SIR1SAR_FR_20130303T030418_20130303T030503_C001.DBL.nc"
processing C:\Users\hans\.dedop\workspaces\aaa\inputs\CS_LTA__SIR1SAR_FR_20130303T030418_20130303T030503_C001.DBL.nc using "default"
processing: done
dedop run: error: list index out of range
```

#### With DeDop Studio
1. Download this [L1A input file](http://dedop.org/data/resources/Amazon/CS_LTA__SIR1SAR_FR_20150331T034023_20150331T034235_C001.DBL.nc)
2. In DeDop Studio, run a process for those files with default configuration

#### With DeDop Core
1. Run in DeDop Shell `dedop run -i "\path\to\CS_LTA__SIR1SAR_FR_20130303T030418_20130303T030503_C001.DBL.nc"`

### Specifications 

DeDop-core: v1.1.0 (based on this commit https://github.com/DeDop/dedop-core/commit/8c2249285f684894983cc9281d2a5d84d1348809)
DeDop-studio: v1.1.0
OS: Windows 10

**Comment by mark-ep** [comment] 2017-09-12 16:23
This issue was caused by the update to the beam angle algorithm, but the root cause was the fact that the doppler angle wasn't being calculated correctly. This should now be fixed in commit 2f34aaf

**Closed by mark-ep** 2017-09-12 16:23 UTC
